sudo: required
language: python
python:
 - "2.7"
 - "3.4"
before_install:
 - sudo apt-get update
 - sudo apt-get install libgdal1-dev libgdal1h
install:
 - pip install requests
script:
 - python setup.py test
