sudo: false
language: python
python:
 - "3.4"
 - "3.5"
 - "3.6"
env:
 - ""
 - LINT="pip install flake8"
addons:
  apt:
    packages:
      - libgdal1-dev
      - libgdal1h
install:
 - pip install requests "pandas==0.20.3"
 - $LINT
script:
 - ./runtests.sh
